name: Build and Publish NuGet Package

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAJOR: '8'
      MINOR: '0'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine semantic version
        id: semver
        uses: simplify9/sw-workflows/actions/determine-semver@main
        with:
          major: ${{ env.MAJOR }}
          minor: ${{ env.MINOR }}

      - name: Dotnet Restore, Build, and Test
        uses: simplify9/sw-workflows/actions/dotnet-build@main
        with:
          projects: "**/*.csproj"
          test-projects: "**/*UnitTests/*.csproj"
          configuration: "Release"
          dotnet-version: "8.0.x"
          run-tests: 'false'

      - name: Pack and Push SimplyWorks.Scheduler.Sdk
        uses: simplify9/sw-workflows/actions/dotnet-pack-push@main
        with:
          projects: "SW.Scheduler.Sdk/SW.Scheduler.Sdk.csproj"
          configuration: "Release"
          version: ${{ steps.semver.outputs.version }}
          api-key: ${{ secrets.SWNUGETKEY }}
          nuget-source: "https://api.nuget.org/v3/index.json"

      - name: Pack and Push SimplyWorks.Scheduler
        uses: simplify9/sw-workflows/actions/dotnet-pack-push@main
        with:
          projects: "SW.Scheduler/SW.Scheduler.csproj"
          configuration: "Release"
          version: ${{ steps.semver.outputs.version }}
          api-key: ${{ secrets.SWNUGETKEY }}
          nuget-source: "https://api.nuget.org/v3/index.json"

      - name: Pack and Push SimplyWorks.Scheduler.EfCore
        uses: simplify9/sw-workflows/actions/dotnet-pack-push@main
        with:
          projects: "SW.Scheduler.EfCore/SW.Scheduler.EfCore.csproj"
          configuration: "Release"
          version: ${{ steps.semver.outputs.version }}
          api-key: ${{ secrets.SWNUGETKEY }}
          nuget-source: "https://api.nuget.org/v3/index.json"

      - name: Pack and Push SimplyWorks.Scheduler.PgSql
        uses: simplify9/sw-workflows/actions/dotnet-pack-push@main
        with:
          projects: "SW.Scheduler.PgSql/SW.Scheduler.PgSql.csproj"
          configuration: "Release"
          version: ${{ steps.semver.outputs.version }}
          api-key: ${{ secrets.SWNUGETKEY }}
          nuget-source: "https://api.nuget.org/v3/index.json"

      - name: Pack and Push SimplyWorks.Scheduler.SqlServer
        uses: simplify9/sw-workflows/actions/dotnet-pack-push@main
        with:
          projects: "SW.Scheduler.SqlServer/SW.Scheduler.SqlServer.csproj"
          configuration: "Release"
          version: ${{ steps.semver.outputs.version }}
          api-key: ${{ secrets.SWNUGETKEY }}
          nuget-source: "https://api.nuget.org/v3/index.json"

      - name: Pack and Push SimplyWorks.Scheduler.MySql
        uses: simplify9/sw-workflows/actions/dotnet-pack-push@main
        with:
          projects: "SW.Scheduler.MySql/SW.Scheduler.MySql.csproj"
          configuration: "Release"
          version: ${{ steps.semver.outputs.version }}
          api-key: ${{ secrets.SWNUGETKEY }}
          nuget-source: "https://api.nuget.org/v3/index.json"

      - name: Pack and Push SimplyWorks.Scheduler.Viewer
        uses: simplify9/sw-workflows/actions/dotnet-pack-push@main
        with:
          projects: "SW.Scheduler.Viewer/SW.Scheduler.Viewer.csproj"
          configuration: "Release"
          version: ${{ steps.semver.outputs.version }}
          api-key: ${{ secrets.SWNUGETKEY }}
          nuget-source: "https://api.nuget.org/v3/index.json"

      - name: Tag new version on GitHub origin
        uses: simplify9/sw-workflows/actions/tag-github-origin@main
        with:
          github-token: ${{ secrets.S9_GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          tag: ${{ steps.semver.outputs.version }}
          sha: ${{ github.sha }}
